# Generated by Django 4.0.3 on 2022-03-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='article',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
